### ISSUE TITLE
aparte module

### ISSUE THREAD

**Issue by Mokerstier** [lars-ruijs/progressive-web-apps-2021#7]
https://github.com/lars-ruijs/progressive-web-apps-2021/blob/9a18435407a4d792614d2cc84d34b7a38ea56ca1/app.js#L20-L32

Misschien een idee om dit nog in een aparte module te zetten. (mapje routes?)

**Comment by Mokerstier** [comment]
kijk anders even bij je booy Joordy: https://github.com/joordy/PhotoPaint-PWA/blob/master/src/routes/router.js
hij heeft een goeie aanpak neergezet

**Comment by lars-ruijs** [comment]
Fixed!
