### ISSUE TITLE
Serverside secrets

### ISSUE THREAD

**Issue by Mokerstier** [lars-ruijs/progressive-web-apps-2021#9]
https://github.com/lars-ruijs/progressive-web-apps-2021/blob/9a18435407a4d792614d2cc84d34b7a38ea56ca1/modules/helpers.js#L5

Omdat je nu op een server je logica uitvoert kun je dit soort "geheimen" beter in een .env opslaan zodat je ze niet openbaar hoeft te zetten.

Maakt voor deze api waarschijnlijk niet zoveel uit maar eigenlijk wil je je persoonlijke keys voor jezelf houden.

tip: check even dotenv op npm daar staat wat je moet doen!
[Hier een luie link voor geen-zin-om-te-googlen](https://www.npmjs.com/package/dotenv)

**Comment by lars-ruijs** [comment]
Bedankt voor de tip! Ik heb .env nu geïmplementeerd.
